name: ybshift
channels:
  - defaults
dependencies:
  - python=3.11.3
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2023.5.7
  - cffi=1.15.1
  - libffi=3.4.4
  - openssl=1.1.1t
  - pip=23.0.1
  - setuptools=66.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
    - asgiref==3.6.0
    - azure-core==1.26.4
    - azure-storage-blob==12.16.0
    - charset-normalizer==3.1.0
    - coreapi==2.3.3
    - coreschema==0.0.4
    - cryptography==40.0.2
    - defusedxml==0.7.1
    - django==4.2.1
    - django-allauth==0.54.0
    - django-cors-headers==4.0.0
    - django-filter==23.2
    - django-storages==1.13.2
    - djangorestframework==3.14.0
    - djangorestframework-simplejwt==5.2.2
    - idna==3.4
    - isodate==0.6.1
    - itypes==1.2.0
    - jinja2==3.1.2
    - markdown==3.4.3
    - markupsafe==2.1.2
    - oauthlib==3.2.2
    - pillow==9.5.0
    - pycparser==2.21
    - pyjwt==2.7.0
    - python3-openid==3.2.0
    - pytz==2023.3
    - requests==2.30.0
    - requests-oauthlib==1.3.1
    - six==1.16.0
    - sqlparse==0.4.4
    - typing-extensions==4.5.0
    - tzdata==2023.3
    - uritemplate==4.1.1
    - urllib3==2.0.2
