# Generated by Django 4.2.1 on 2023-05-18 09:16

import app1.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Table_personalLink",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("link", models.URLField()),
                ("description", models.CharField(max_length=500)),
                ("footnote", models.CharField(max_length=500)),
                (
                    "pic",
                    models.ImageField(
                        blank=True, null=True, upload_to=app1.models.user_directory_path
                    ),
                ),
                ("click", models.IntegerField(default=0)),
                ("startDate", models.DateField()),
                ("endDate", models.DateField()),
                ("show", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Table_businessCard",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to=app1.models.user_directory_path
                    ),
                ),
                (
                    "background",
                    models.ImageField(
                        blank=True, null=True, upload_to=app1.models.user_directory_path
                    ),
                ),
                ("color", models.CharField(max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
