# Generated by Django 4.2.1 on 2023-05-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="table_businesscard", name="email",),
        migrations.AlterField(
            model_name="table_businesscard",
            name="color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
