# Generated by Django 4.2.1 on 2023-05-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_remove_table_businesscard_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table_businesscard",
            name="color",
            field=models.CharField(default="#0068bd", max_length=20),
        ),
    ]
