# Generated by Django 4.2.1 on 2023-05-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_alter_table_businesscard_color_table_linkipclick"),
    ]

    operations = [
        migrations.AddField(
            model_name="table_linkipclick",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
