# Generated by Django 4.2.1 on 2023-05-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_table_linkipclick_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table_linkipclick",
            name="count",
            field=models.IntegerField(default=1),
        ),
    ]
